version: "3.2"

services:
  db:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_DB_HOST=typeorm
      - POSTGRES_DB=typeorm
      - POSTGRES_USER=typeorm
      - POSTGRES_PASSWORD=typeorm
      - POSTGRES_DB_PORT=5432
    ports:
      - 15432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
